### ISSUE TITLE
I Maintain a Similar Project and some Resources that you might find useful

### ISSUE THREAD

**Issue by cyberpunk2350** [VITALISED/Atlan#1]
Hello Will,
I'm working on a few projects with the NMSCD (https://github.com/NMSCD) that you might find useful or interested in contributing too.
these include a similar offline/drop in discovery server replacement, and a fully documented API resources for the NMS discovery servers..
at the moment, these projects are set to private, due to a request by HG, however if you would be interested in taking a look feel free to hit me up.
Github/Discord/Twitter - @cyberpunk2350
Mastodon - @cyberpunk2350@nomanssky.social
other contacts - https://cyberpunk2350.com
--_Henry/Cyberpunk2350_

**Comment by VITALISED** [comment]
![ezgif com-gif-maker](https://github.com/VITALISED/Atlan/assets/39478251/8e6e0d0f-bd04-4ff6-88c8-a9f82db6f052)

**Comment by VITALISED** [comment]
Sure add me on discord @vitalised

**Comment by cyberpunk2350** [comment]
Sent you invites and a discord message
